Repository redBorder/redborder-proxy, pull requests merged in 2023-11, with the labels that each got.

#8 Rhel9
  packaging/rpm/redborder-proxy.spec
  resources/lib/rb_wiz_lib.rb
  resources/scripts/rb_init_conf.rb
Labels: kind/bug, size/S

#9 Feature/#15799 add network scripts
  packaging/rpm/redborder-proxy.spec
  resources/scripts/rb_init_conf.rb
Labels: size/S, kind/feature

#10 Add dhclient package
  packaging/rpm/redborder-proxy.spec
Labels: kind/feature, size/XS

#11 release 0.0.9
  packaging/rpm/redborder-proxy.spec
Labels: size/XS, kind/documentation
